name: hhs-scraper

on:
  #push:
  workflow_dispatch:
  schedule:
    - cron: '15 17 * * *' # runs at 10:15 a.m. MT, since data updates at noon EST

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' # install the python version needed #3.9.9 #3.7.7
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run sj-gobierno.py to get the latest data
        #env: 
        #  EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        #  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        #  EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: python hhs-scraper.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          #git commit -m "update data" -a
          #git add --all
          git commit -am "Latest data: $(date)"
          #git push origin main
        #env:
        #  REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        #  username: github-actions
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
